---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudbowl-battle
  # name: cloudbowl-battle
  name: cloudbowl-battle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbowl-battle
  template:
    metadata:
      labels:
        app: cloudbowl-battle
    spec:
      containers:
      - name: cloudbowl-microservice-game
        image: us-central1-docker.pkg.dev/hackathon-350614/container/cloudbowl-microservice-game:1.6
        imagePullPolicy: IfNotPresent
        command: ["battle"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
#          value: 34.133.211.208:9094
#          value: cloudbowl-kafka-external-bootstrap.kafka:9094
          value: cloudbowl-kafka-bootstrap.kafka:9092
        - name: JAVA_OPTS
          value: "-Xmx6g"
        resources:
          requests:
            cpu: "1"
            memory: "10Gi"
          limits:
            cpu: "2"
            memory: "10Gi"
          