---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudbowl-battle
  name: cloudbowl-battle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbowl-battle
  template:
    metadata:
      labels:
        app: cloudbowl-battle
    spec:
      containers:
      - name: cloudbowl-microservice-game
        image: us-central1-docker.pkg.dev/hackathon-350614/container/cloudbowl-microservice-game:dea93a0243639ad88962775e48da6b5590c38b8d
        imagePullPolicy: IfNotPresent
        command: ["battle"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: cloudbowl-kafka-bootstrap.kafka:9091
        # - name: JAVA_TOOL_OPTIONS
        #   value: "-Xmx2g -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8"
        resources:
          requests:
            cpu: "2"
            memory: 2Gi