apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: player-update
  namespace: kafka
  labels:
    strimzi.io/cluster: cloudbowl
spec:
  partitions: 10
  replicas: 2
  config:
      retention.ms: -1
      retention.bytes: -1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: arena-config
  namespace: kafka
  labels:
    strimzi.io/cluster: cloudbowl
spec:
  partitions: 10
  replicas: 2
  config:
      retention.ms: -1
      retention.bytes: -1
      cleanup.policy: compact
      delete.retention.ms: 100
      segment.ms: 100
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: viewer-ping
  namespace: kafka
  labels:
    strimzi.io/cluster: cloudbowl
spec:
  partitions: 10
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: arena-update
  namespace: kafka
  labels:
    strimzi.io/cluster: cloudbowl
spec:
  partitions: 10
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: scores-reset
  namespace: kafka
  labels:
    strimzi.io/cluster: cloudbowl
spec:
  partitions: 10
  replicas: 2