---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudbowl-web
  name: cloudbowl-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudbowl-web
  template:
    metadata:
      labels:
        app: cloudbowl-web
    spec:
      containers:
      - name: cloudbowl-microservice-game
        image: us-central1-docker.pkg.dev/hackathon-350614/container/cloudbowl-microservice-game:1.6
        imagePullPolicy: IfNotPresent
        command: ["web"]
        env:
        - name: PORT
          value: "8080"
        - name: KAFKA_BOOTSTRAP_SERVERS
#          value: 34.133.211.208:9094
#          value: cloudbowl-kafka-external-bootstrap.kafka:9094
          value: cloudbowl-kafka-bootstrap.kafka:9092
        - name: JAVA_OPTS
          value: "-Xmx6g"
        - name: WEBJARS_USE_CDN
          valueFrom:
            configMapKeyRef:
              key: WEBJARS_USE_CDN
              name: cloudbowl-config
        - name: APPLICATION_SECRET
          valueFrom:
            configMapKeyRef:
              key: APPLICATION_SECRET
              name: cloudbowl-config
        - name: ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: ADMIN_PASSWORD
              name: cloudbowl-config

        resources:
          requests:
            cpu: "1"
            memory: "10Gi"
          limits:
            cpu: "2"
            memory: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbowl-web
  labels:
    name: cloudbowl-web
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: cloudbowl-web
  type: LoadBalancer